spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true

  sql:
    init:
      mode: embedded

blog:
  jwt-key: "hR7Go0KFDhBk5jl0J2ht0Q6B7LtK/TKhiU3GAlHte2c="