### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "woniwoni@gmail.com",
  "password": "1234"
}

### 인증 페이지 요청

GET http://localhost:8080/foo
Content-Type: application/json
Cookie: SESSION=4f44ef61-9f7d-4ac2-a06a-355cc6482558