### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "woniwoni@gmail.com",
  "password": "1234"
}

### 인증 페이지 요청

GET http://localhost:8080/foo
Content-Type: application/json
Cookie: SESSION=ccc59e4c-710f-459a-9921-a3e26f5565d6;